# Handling Date and Time Variables

In [1]:
import numpy as np
import pandas as pd

In [25]:
date = pd.read_csv('../datasets/orders.csv')
time = pd.read_csv('../datasets/messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with Dates

In [26]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [27]:
date['date_year'] =  date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
888 2019-11-09        6850        1       2       2019
207 2019-04-01        5135        9       5       2019
308 2018-07-27         664       24      15       2018
580 2018-09-29        5965       13       2       2018
973 2018-09-08         547        4      19       2018

### 2. Extract Month

In [28]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [29]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

### 3.Extract Days

In [30]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [31]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [32]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [33]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

### Extract week of the year

In [35]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

### Extract Quarter

In [36]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

### Extract Semester

In [37]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

### Extract Time elapsed between dates

In [38]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 4, 20, 22, 25, 56, 797526)

In [39]:
today - date['date']

0     2323 days 22:25:56.797526
1     2805 days 22:25:56.797526
2     2736 days 22:25:56.797526
3     2438 days 22:25:56.797526
4     2661 days 22:25:56.797526
                 ...
995   2751 days 22:25:56.797526
996   2692 days 22:25:56.797526
997   2540 days 22:25:56.797526
998   2605 days 22:25:56.797526
999   2379 days 22:25:56.797526
Name: date, Length: 1000, dtype: timedelta64[ns]

In [40]:
(today - date['date']).dt.days

0      2323
1      2805
2      2736
3      2438
4      2661
       ...
995    2751
996    2692
997    2540
998    2605
999    2379
Name: date, Length: 1000, dtype: int64

In [43]:
# Months passed

date['months_passed'] = np.round((today - date['date']).dt.days / 30.44, 0)

In [44]:
date

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2,76.0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2,92.0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2,90.0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2,80.0
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8,0,Monday,0,41,4,2,90.0
996,2018-12-06,5521,7,1,2018,12,December,6,3,Thursday,0,49,4,2,88.0
997,2019-05-07,487,26,14,2019,5,May,7,1,Tuesday,0,19,2,1,83.0
998,2019-03-03,1503,21,2,2019,3,March,3,6,Sunday,1,9,1,1,86.0
999,2019-10-15,6371,7,22,2019,10,October,15,1,Tuesday,0,42,4,2,78.0

## Time

In [45]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [46]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [47]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [48]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### Extract Time part

In [49]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### Time difference

In [50]:
today - time['date']

0     4509 days 21:35:56.797526
1     4373 days 22:45:56.797526
2     4859 days 22:04:56.797526
3     4161 days 21:54:56.797526
4     4558 days 23:14:56.797526
                 ...
995   5148 days 21:35:56.797526
996   4469 days 23:11:56.797526
997   4934 days 22:48:56.797526
998   5050 days 22:51:56.797526
999   4322 days 23:00:56.797526
Name: date, Length: 1000, dtype: timedelta64[ns]

In [51]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.896554e+08
1      3.779092e+08
2      4.198971e+08
3      3.595893e+08
4      3.938949e+08
           ...
995    4.448650e+08
996    3.862051e+08
997    4.263797e+08
998    4.364023e+08
999    3.735037e+08
Name: date, Length: 1000, dtype: float64

In [52]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.494256e+06
1      6.298486e+06
2      6.998285e+06
3      5.993155e+06
4      6.564915e+06
           ...
995    7.414416e+06
996    6.436752e+06
997    7.106329e+06
998    7.273372e+06
999    6.225061e+06
Name: date, Length: 1000, dtype: float64

In [53]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      108237.599110
1      104974.765777
2      116638.082444
3       99885.915777
4      109415.249110
           ...
995    123573.599110
996    107279.199110
997    118438.815777
998    121222.865777
999    103751.015777
Name: date, Length: 1000, dtype: float64